### ISSUE TITLE
'CoinMarketCapAPI' is not defined

### ISSUE THREAD

**Issue by tifDev** [Lucas170/CoinMarketCap-API-An-Introductory-Guide#1]
Hi,

I was following your tutorial at https://algotrading101.com/learn/coinmarketcap-api-guide/ , but I'm getting this error:

```
Traceback (most recent call last):
  File "coinmarketcapapi.py", line 7, in <module>
    import coinmarketcapapi
  File "/home/we/Downloads/crypto-apis/coinmarketcapapi.py", line 14, in <module>
    cmc = CoinMarketCapAPI(key)
NameError: name 'CoinMarketCapAPI' is not defined
```

Here is my code:

```
rom requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json
import pprint 
import os
import coinmarketcapapi

key='xxxx' # API key

pp = pprint.PrettyPrinter(indent=4)

cmc = CoinMarketCapAPI(key)
data_quote = cmc.cryptocurrency_quotes_latest(symbol='ETH', convert='EUR')
pp.pprint(data_quote)

```

Why it's showing this error?

**Comment by Lucas170** [comment]
Thanks for the spot!

`cmc = CoinMarketCapAPI(key)`

should be 

`cmc = coinmarketcapapi.CoinMarketCapAPI(key)`
